[2024-11-24T20:36:12.793+0000] {processor.py:186} INFO - Started process (PID=120) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:36:12.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:36:12.799+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:36:12.798+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:36:12.831+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:36:12.825+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:36:12.833+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:36:12.981+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.197 seconds
[2024-11-24T20:36:44.651+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:36:44.886+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:36:44.888+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:36:44.888+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:36:45.091+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:36:45.085+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:36:45.092+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:36:54.324+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 9.683 seconds
[2024-11-24T20:37:25.166+0000] {processor.py:186} INFO - Started process (PID=270) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:37:25.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:37:25.170+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:37:25.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:37:25.195+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:37:25.188+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:37:25.196+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:37:32.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 7.022 seconds
[2024-11-24T20:38:02.669+0000] {processor.py:186} INFO - Started process (PID=342) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:38:02.671+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:38:02.675+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:38:02.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:38:02.708+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:38:02.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:38:02.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:38:03.532+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.872 seconds
[2024-11-24T20:38:33.655+0000] {processor.py:186} INFO - Started process (PID=414) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:38:33.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:38:33.660+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:38:33.660+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:38:33.687+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:38:33.682+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:38:33.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:38:34.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.943 seconds
[2024-11-24T20:39:05.272+0000] {processor.py:186} INFO - Started process (PID=486) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:39:05.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:39:05.277+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:39:05.276+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:39:05.307+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:39:05.300+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:39:05.308+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:39:06.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 1.467 seconds
[2024-11-24T20:39:36.833+0000] {processor.py:186} INFO - Started process (PID=557) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:39:36.834+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:39:36.836+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:39:36.836+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:39:36.857+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:39:36.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:39:36.858+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:39:38.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 1.181 seconds
[2024-11-24T20:40:08.102+0000] {processor.py:186} INFO - Started process (PID=629) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:40:08.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:40:08.107+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:40:08.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:40:08.779+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:40:08.773+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:40:08.898+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:40:09.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.984 seconds
[2024-11-24T20:40:39.307+0000] {processor.py:186} INFO - Started process (PID=700) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:40:39.310+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:40:39.313+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:40:39.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:40:39.341+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:40:39.335+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:40:39.342+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:40:39.423+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.125 seconds
[2024-11-24T20:41:09.602+0000] {processor.py:186} INFO - Started process (PID=772) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:41:10.336+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:41:10.339+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:41:10.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:41:10.363+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:41:10.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:41:10.364+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:41:10.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.962 seconds
[2024-11-24T20:41:41.340+0000] {processor.py:186} INFO - Started process (PID=844) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:41:41.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:41:41.343+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:41:41.343+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:41:41.369+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:41:41.363+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:41:41.371+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:41:41.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.092 seconds
[2024-11-24T20:42:11.684+0000] {processor.py:186} INFO - Started process (PID=916) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:42:11.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:42:11.690+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:42:11.689+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:42:11.713+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:42:11.708+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:42:11.714+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:42:13.222+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 1.546 seconds
[2024-11-24T20:42:43.712+0000] {processor.py:186} INFO - Started process (PID=988) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:42:43.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:42:43.716+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:42:43.716+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:42:43.742+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:42:43.735+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:42:43.743+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:42:43.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.096 seconds
[2024-11-24T20:43:13.887+0000] {processor.py:186} INFO - Started process (PID=1060) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:43:13.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:43:13.895+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:43:13.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:43:13.974+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:43:13.969+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:43:13.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:43:14.024+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.144 seconds
[2024-11-24T20:43:44.273+0000] {processor.py:186} INFO - Started process (PID=1132) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:43:44.275+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:43:44.278+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:43:44.278+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:43:44.303+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:43:44.297+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:43:44.305+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:43:44.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.100 seconds
[2024-11-24T20:44:15.166+0000] {processor.py:186} INFO - Started process (PID=1204) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:44:15.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T20:44:15.171+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:44:15.171+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:44:15.197+0000] {logging_mixin.py:190} INFO - [2024-11-24T20:44:15.191+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-11-24T20:44:15.199+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T20:44:15.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.730 seconds
[2024-11-24T21:36:15.115+0000] {processor.py:186} INFO - Started process (PID=1023) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:36:15.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T21:36:15.121+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:36:15.121+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:36:15.148+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:36:15.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
[2024-11-24T21:36:15.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:36:16.734+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 1.629 seconds
[2024-11-24T21:38:37.231+0000] {processor.py:186} INFO - Started process (PID=491) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:38:37.242+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T21:38:37.245+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:38:37.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:38:37.300+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:38:37.283+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
[2024-11-24T21:38:37.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:38:37.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.122 seconds
[2024-11-24T21:39:08.117+0000] {processor.py:186} INFO - Started process (PID=563) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:39:08.118+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T21:39:08.121+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:39:08.120+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:39:08.397+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:39:08.389+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
[2024-11-24T21:39:08.398+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:39:08.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.350 seconds
[2024-11-24T21:39:39.440+0000] {processor.py:186} INFO - Started process (PID=635) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:39:39.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T21:39:39.443+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:39:39.443+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:39:39.471+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:39:39.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
[2024-11-24T21:39:39.472+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:39:40.419+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.985 seconds
[2024-11-24T21:40:11.032+0000] {processor.py:186} INFO - Started process (PID=707) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:40:11.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T21:40:11.036+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:40:11.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:40:11.251+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:40:11.244+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
[2024-11-24T21:40:11.252+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:40:11.393+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.366 seconds
[2024-11-24T21:40:41.920+0000] {processor.py:186} INFO - Started process (PID=779) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:40:41.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T21:40:41.924+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:40:41.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:40:41.948+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:40:41.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
[2024-11-24T21:40:41.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:40:42.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.088 seconds
[2024-11-24T21:41:12.951+0000] {processor.py:186} INFO - Started process (PID=851) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:41:12.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T21:41:12.954+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:41:12.954+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:41:12.986+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:41:12.980+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
[2024-11-24T21:41:12.987+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:41:14.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 1.202 seconds
[2024-11-24T21:41:44.297+0000] {processor.py:186} INFO - Started process (PID=923) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:41:44.298+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T21:41:44.301+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:41:44.300+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:41:44.326+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:41:44.320+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
[2024-11-24T21:41:44.327+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:41:44.373+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.082 seconds
[2024-11-24T21:42:14.747+0000] {processor.py:186} INFO - Started process (PID=995) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:42:14.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T21:42:14.751+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:42:14.750+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:42:14.780+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:42:14.773+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
[2024-11-24T21:42:14.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:42:14.832+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.093 seconds
[2024-11-24T21:42:45.627+0000] {processor.py:186} INFO - Started process (PID=1067) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:42:45.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T21:42:45.631+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:42:45.630+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:42:45.659+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:42:45.652+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
[2024-11-24T21:42:45.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:42:45.702+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.083 seconds
[2024-11-24T21:43:16.332+0000] {processor.py:186} INFO - Started process (PID=1139) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:43:16.334+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T21:43:16.336+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:43:16.336+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:43:16.365+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:43:16.359+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
[2024-11-24T21:43:16.366+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:43:16.441+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.115 seconds
[2024-11-24T21:43:46.568+0000] {processor.py:186} INFO - Started process (PID=1211) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:43:46.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T21:43:46.572+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:43:46.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:43:46.597+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:43:46.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
[2024-11-24T21:43:46.598+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:43:46.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.406 seconds
[2024-11-24T21:44:17.255+0000] {processor.py:186} INFO - Started process (PID=1283) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:44:17.257+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T21:44:17.261+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:44:17.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:44:17.289+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:44:17.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
[2024-11-24T21:44:17.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:44:17.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.460 seconds
[2024-11-24T21:44:47.845+0000] {processor.py:186} INFO - Started process (PID=1355) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:44:47.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-24T21:44:47.849+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:44:47.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:44:47.869+0000] {logging_mixin.py:190} INFO - [2024-11-24T21:44:47.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 3, in <module>
    import cv2
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/airflow/.local/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
[2024-11-24T21:44:47.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-24T21:44:47.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.125 seconds
