[2024-11-19T18:06:11.528+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-19T18:06:11.552+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_to_google_sheets_dag.load_data manual__2024-11-19T18:06:04.630116+00:00 [queued]>
[2024-11-19T18:06:11.565+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_to_google_sheets_dag.load_data manual__2024-11-19T18:06:04.630116+00:00 [queued]>
[2024-11-19T18:06:11.565+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-19T18:06:11.616+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2024-11-19 18:06:04.630116+00:00
[2024-11-19T18:06:11.625+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=104) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-19T18:06:11.628+0000] {standard_task_runner.py:72} INFO - Started process 113 to run task
[2024-11-19T18:06:11.628+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'upload_to_google_sheets_dag', 'load_data', 'manual__2024-11-19T18:06:04.630116+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/Zad3.py', '--cfg-path', '/tmp/tmpjnps6vz3']
[2024-11-19T18:06:11.629+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask load_data
[2024-11-19T18:06:11.717+0000] {task_command.py:467} INFO - Running <TaskInstance: upload_to_google_sheets_dag.load_data manual__2024-11-19T18:06:04.630116+00:00 [running]> on host 5dfac9e274c2
[2024-11-19T18:06:11.931+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_to_google_sheets_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T18:06:04.630116+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-19T18:06:04.630116+00:00'
[2024-11-19T18:06:11.933+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-19T18:06:11.933+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-19T18:06:11.934+0000] {logging_mixin.py:190} INFO - Current task name:load_data state:running start_date:2024-11-19 18:06:11.552993+00:00
[2024-11-19T18:06:11.935+0000] {logging_mixin.py:190} INFO - Dag name:upload_to_google_sheets_dag and current dag run status:running
[2024-11-19T18:06:11.935+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-19T18:06:11.937+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Zad3.py", line 87, in load_data_task
    data = load_data_with_paths(image_folder, annotation_folder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Zad3.py", line 54, in load_data_with_paths
    for breed_folder in os.listdir(image_folder):
                        ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './opt/airflow/dags/images/Images'
[2024-11-19T18:06:11.958+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-19T18:06:11.959+0000] {logging_mixin.py:190} INFO - Task start:2024-11-19 18:06:11.552993+00:00 end:2024-11-19 18:06:11.957393+00:00 duration:0.4044
[2024-11-19T18:06:11.960+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_data> dag:<DAG: upload_to_google_sheets_dag> dagrun:<DagRun upload_to_google_sheets_dag @ 2024-11-19 18:06:04.630116+00:00: manual__2024-11-19T18:06:04.630116+00:00, state:running, queued_at: 2024-11-19 18:06:05.039514+00:00. externally triggered: True>
[2024-11-19T18:06:11.961+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: './opt/***/dags/images/Images'
[2024-11-19T18:06:11.962+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_to_google_sheets_dag, task_id=load_data, run_id=manual__2024-11-19T18:06:04.630116+00:00, execution_date=20241119T180604, start_date=20241119T180611, end_date=20241119T180611
[2024-11-19T18:06:12.014+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-19T18:06:12.015+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task load_data ([Errno 2] No such file or directory: './opt/airflow/dags/images/Images'; 113)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Zad3.py", line 87, in load_data_task
    data = load_data_with_paths(image_folder, annotation_folder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Zad3.py", line 54, in load_data_with_paths
    for breed_folder in os.listdir(image_folder):
                        ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './opt/airflow/dags/images/Images'
[2024-11-19T18:06:12.046+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-19T18:06:12.079+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-19T18:06:12.108+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
