[2024-11-19T18:21:04.037+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-19T18:21:04.069+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_to_google_sheets_dag.split_data manual__2024-11-19T18:20:50.996711+00:00 [queued]>
[2024-11-19T18:21:04.088+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_to_google_sheets_dag.split_data manual__2024-11-19T18:20:50.996711+00:00 [queued]>
[2024-11-19T18:21:04.089+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-19T18:21:04.215+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): split_data> on 2024-11-19 18:20:50.996711+00:00
[2024-11-19T18:21:04.225+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=368) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-19T18:21:04.228+0000] {standard_task_runner.py:72} INFO - Started process 377 to run task
[2024-11-19T18:21:04.228+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'upload_to_google_sheets_dag', 'split_data', 'manual__2024-11-19T18:20:50.996711+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/Zad3.py', '--cfg-path', '/tmp/tmpqnllyfv_']
[2024-11-19T18:21:04.229+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask split_data
[2024-11-19T18:21:04.327+0000] {task_command.py:467} INFO - Running <TaskInstance: upload_to_google_sheets_dag.split_data manual__2024-11-19T18:20:50.996711+00:00 [running]> on host 5dfac9e274c2
[2024-11-19T18:21:04.565+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_to_google_sheets_dag' AIRFLOW_CTX_TASK_ID='split_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T18:20:50.996711+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-19T18:20:50.996711+00:00'
[2024-11-19T18:21:04.566+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-19T18:21:04.567+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-19T18:21:04.567+0000] {logging_mixin.py:190} INFO - Current task name:split_data state:running start_date:2024-11-19 18:21:04.070456+00:00
[2024-11-19T18:21:04.568+0000] {logging_mixin.py:190} INFO - Dag name:upload_to_google_sheets_dag and current dag run status:running
[2024-11-19T18:21:04.568+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-19T18:21:04.569+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: split_data_task() missing 1 required positional argument: 'data_dict'
[2024-11-19T18:21:04.591+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-19T18:21:04.592+0000] {logging_mixin.py:190} INFO - Task start:2024-11-19 18:21:04.070456+00:00 end:2024-11-19 18:21:04.590040+00:00 duration:0.519584
[2024-11-19T18:21:04.593+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): split_data> dag:<DAG: upload_to_google_sheets_dag> dagrun:<DagRun upload_to_google_sheets_dag @ 2024-11-19 18:20:50.996711+00:00: manual__2024-11-19T18:20:50.996711+00:00, state:running, queued_at: 2024-11-19 18:20:51.018610+00:00. externally triggered: True>
[2024-11-19T18:21:04.594+0000] {logging_mixin.py:190} INFO - Failure caused by split_data_task() missing 1 required positional argument: 'data_dict'
[2024-11-19T18:21:04.595+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_to_google_sheets_dag, task_id=split_data, run_id=manual__2024-11-19T18:20:50.996711+00:00, execution_date=20241119T182050, start_date=20241119T182104, end_date=20241119T182104
[2024-11-19T18:21:04.677+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-19T18:21:04.678+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 27 for task split_data (split_data_task() missing 1 required positional argument: 'data_dict'; 377)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: split_data_task() missing 1 required positional argument: 'data_dict'
[2024-11-19T18:21:04.725+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-19T18:21:04.762+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-19T18:21:04.805+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
